### PR TITLE
feat: add skeleton component

### PR DESCRIPTION
**Pull request by jayala**
Happy New Year! Based on the [NativeBase Skeleton](https://docs.nativebase.io/skeleton) component, I added the same for GlueStack with the new patterns.

### CODE REVIEW

**Comment by Viraj-10** [comment]
Hey @jayala, Thanks for creating a PR for new Component. It's a best new year gift for us. 
We will review this once and if everything look we will merge it.

**Comment by vaniyokk** [comment]
Thank you! Really missing this component!

**Comment by Axolem** [comment]
Really want this component, can it be on the next release please

**Comment by andre-vg** [comment]
Nice work, really needing this feat.

**Comment by sem4phor** [comment]
I believe putting it into the examples / storybook would also be great :)

**Comment by adr-iova** [comment]
any updates on this?

**Comment by DiogoKaster** [comment]
Looking forward for this component, any plans to merge it soon? It's been 3 months since the pull request.

**Comment by akinzalowevidation** [comment]
Is there a reason this was never merged?

**Comment by Viraj-10** [comment]
Skeleton is live with `gluestack-ui-v2`

**Pull request closed without merging**
