### PR TITLE
feat: added indeterminate state

### PR DESCRIPTION
**Pull request by Viraj-10**
### Checkbox
- [x]  Support for `Indeterminate` Icon
- [x] Fix `Indeterminate` style in config.
- [ ] Update Figma file. 
- [ ] Update Spec Docs.

### Radio
- [x]  Support for `Indeterminate` Icon
- [ ] Fix `Indeterminate` style in config.
- [ ] Update Figma file. 
- [ ] Update Spec Docs.

### CODE REVIEW

**Comment by doodle-codes** [comment]
Is there any progress to this PR?

**Comment by doodle-codes** [comment]
Please, can someone who is authorized merge this PR. This PR has been open for more than a month and our company is waiting on this fix.

**Comment by doodle-codes** [comment]
Can someone review or finalize this PR?

**Comment by sem4phor** [comment]
@makkarMeenu Any heads up hen this will be progressing? :)

**Pull request closed without merging**
