### PR TITLE
Fixes #2450 -- Actionsheet scroll prevention only when backdrop is used

### LINKED ISSUE #2450: Actionsheet v1 - scroll lock should not kick in if backdrop is not rendered
### Description

When I use the Actionsheet component without a backdrop I can't scroll the page. If I don't use a backdrop I would expect the background scroll to work.

### CodeSandbox/Snack link

n/a

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

@gluestack-ui/actionsheet: 0.2.44

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

### Other Platform

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by FezVrasta**
With this change the scroll is prevented only when the Actionsheet backdrop component is used, allowing the actionsheet to be used to create UIs similar to Apple Maps and many other, where an actionsheet is open while the user is allowed to interact with the rest of the app.

### CODE REVIEW

**Comment by Viraj-10** [comment]
@FezVrasta, This breaks existing behaviour of the component.

**Comment by Viraj-10** [comment]
@FezVrasta, can you introduce a prop in actionsheet `preventScroll` and pass it to in hook like `usePreventScroll({ isDisabled: preventScroll });` this ? Make default value `true` so it doesn't break for other users.

**Comment by FezVrasta** [comment]
Of course. Would you like the backdrop component to also include the `usePreventScroll` so that we can mark the existing ActionSheetContent scroll prevention behavior deprecated?

**Comment by Viraj-10** [comment]
Let's keep it in content and remove it from backdrop

**Comment by FezVrasta** [comment]
I can do it if it means we have a way to make the actionsheet component work for my use case, but it doesn't make much sense from a design perspective. Why the content component should influence the behavior of what's behind it?

**Pull request merged**
