### PR TITLE
Fix/stale state on batch update of toasts

### PR DESCRIPTION
**Pull request by k-v-dimitrov**
**Hi :wave:**

I encountered a similar issue as mentioned in #1543, albeit in a slightly different scenario. After thorough investigation, I identified the root cause and implemented a fix for it.

**Issue**
I reproduced the issue by calling `toast.show()` twice in an useEffect and witnessed that only one was showing. Same experience under 2 setTimeouts.

**Changes Made**
I changed the way toastInfo is updated and now it'll always refer to the prev value provided by the useState's callback. That way we make sure to always have the latest value whilst react is batch updating.

**Testing**
I used expo storybook running on an android device and web.

### CODE REVIEW

**Comment by k-v-dimitrov** [comment]
@Viraj-10

**Comment by k-v-dimitrov** [comment]
@ankit-tailor

**Comment by ankit-tailor** [comment]
Hey @k-v-dimitrov, Thanks for working on the issue. We'll review the PR.

**Comment by k-v-dimitrov** [comment]
Thank you! :+1: I'll be happy to provide further help

**Review by Viraj-10 — APPROVED** [review]

**Pull request merged**
